2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_setup.py:_flush():68] Configure stats pid to 9161
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_setup.py:_flush():68] Loading settings from /home/ketamine/.config/wandb/settings
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_setup.py:_flush():68] Loading settings from /home/ketamine/Documents/Buas/Year2/2024-25-Y2-BlockB/sim/wandb/settings
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:_log_setup():528] Logging user logs to /home/ketamine/Documents/Buas/Year2/2024-25-Y2-BlockB/sim/wandb/run-20241217_162841-23ppt5fz/logs/debug.log
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:_log_setup():529] Logging internal logs to /home/ketamine/Documents/Buas/Year2/2024-25-Y2-BlockB/sim/wandb/run-20241217_162841-23ppt5fz/logs/debug-internal.log
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:init():644] calling init triggers
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:init():680] starting backend
2024-12-17 16:28:41,659 INFO    MainThread:9161 [wandb_init.py:init():684] sending inform_init request
2024-12-17 16:28:41,667 INFO    MainThread:9161 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-17 16:28:41,667 INFO    MainThread:9161 [wandb_init.py:init():697] backend started and connected
2024-12-17 16:28:41,668 INFO    MainThread:9161 [wandb_init.py:init():790] updated telemetry
2024-12-17 16:28:41,675 INFO    MainThread:9161 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-17 16:28:41,675 WARNING MsgRouterThr:9161 [router.py:message_loop():75] message_loop has been closed
2024-12-17 16:28:46,676 ERROR   MainThread:9161 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/ketamine/.conda/envs/Test_pybullet/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/home/ketamine/.conda/envs/Test_pybullet/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
  File "/home/ketamine/.conda/envs/Test_pybullet/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
